### PR TITLE
Dp217 17 show results of questioning

### PR DESCRIPTION
**Pull request by evroandrew**

### CODE REVIEW

**Review by gotoindex — COMMENTED** [review]
- questioning/cron.py def obsolete_records_removal()
  It's a good practice to name methods & functions with verbs. Suggested name:
  remove_obsolete_records()
- enrollment_assistant/models.py
  Not sure why add an empty models.py
- questioning/urls.py
  Not sure why use re_path if a regex function isn't provided
- questioning/views.py
  Recommend moving all non-view methods to a separate file, like services.py
- Recommend renaming url '/questioning/questioning_ajax/' to '/questioning/ajax/'
- users/managers.py
  Recommend removing ugettext_lazy import for now (mainly since a different gettext method migth be used)
- Recommend adding newlines at end of files (both .py and .html ones)

**Review by suslovichb — APPROVED** [review]

**Comment by evroandrew** [comment]
> Not sure why use re_path if a regex function isn't provided

Regex is used. We can go to the questioning/ results / page and see all the results passed and we can enter an additional url to see a specific result.

**Review by suslovichb — APPROVED** [review]

**Review by gotoindex — APPROVED** [review]
- Recommend adding newlines at end of files (both .py and .html ones)

**Review by gotoindex — COMMENTED** [review]
- questioning/urls.py
  Recommend removing unused re_path import

**Review by paivazov — APPROVED** [review]

**Review by gotoindex — APPROVED** [review]

**Pull request merged**
